// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.doctoror.commons.wear.nano;

@SuppressWarnings("hiding")
public interface WearQueueFromSearch {

  public static final class Queue extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Queue[] _emptyArray;
    public static Queue[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Queue[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated int64 queue = 1;
    public long[] queue;

    // optional int64 selectedId = 2;
    public long selectedId;

    public Queue() {
      clear();
    }

    public Queue clear() {
      queue = com.google.protobuf.nano.WireFormatNano.EMPTY_LONG_ARRAY;
      selectedId = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.queue != null && this.queue.length > 0) {
        for (int i = 0; i < this.queue.length; i++) {
          output.writeInt64(1, this.queue[i]);
        }
      }
      if (this.selectedId != 0L) {
        output.writeInt64(2, this.selectedId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.queue != null && this.queue.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.queue.length; i++) {
          long element = this.queue[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt64SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * this.queue.length;
      }
      if (this.selectedId != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.selectedId);
      }
      return size;
    }

    @Override
    public Queue mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 8);
            int i = this.queue == null ? 0 : this.queue.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.queue, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readInt64();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readInt64();
            this.queue = newArray;
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readInt64();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.queue == null ? 0 : this.queue.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.queue, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readInt64();
            }
            this.queue = newArray;
            input.popLimit(limit);
            break;
          }
          case 16: {
            this.selectedId = input.readInt64();
            break;
          }
        }
      }
    }

    public static Queue parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Queue(), data);
    }

    public static Queue parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Queue().mergeFrom(input);
    }
  }
}
