// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.doctoror.fuckoffmusicplayer.data.playback.nano;

@SuppressWarnings("hiding")
public interface PlaybackParamsProto {

  public static final class PlaybackParams extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PlaybackParams[] _emptyArray;
    public static PlaybackParams[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PlaybackParams[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bool shuffle = 1;
    public boolean shuffle;

    // optional int32 repeatMode = 2;
    public int repeatMode;

    public PlaybackParams() {
      clear();
    }

    public PlaybackParams clear() {
      shuffle = false;
      repeatMode = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.shuffle != false) {
        output.writeBool(1, this.shuffle);
      }
      if (this.repeatMode != 0) {
        output.writeInt32(2, this.repeatMode);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.shuffle != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.shuffle);
      }
      if (this.repeatMode != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.repeatMode);
      }
      return size;
    }

    @Override
    public PlaybackParams mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.shuffle = input.readBool();
            break;
          }
          case 16: {
            this.repeatMode = input.readInt32();
            break;
          }
        }
      }
    }

    public static PlaybackParams parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PlaybackParams(), data);
    }

    public static PlaybackParams parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PlaybackParams().mergeFrom(input);
    }
  }
}
