// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.doctoror.fuckoffmusicplayer.playlist.nano;

@SuppressWarnings("hiding")
public interface PersistablePlaylist {

  public static final class ProtoMedia extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ProtoMedia[] _emptyArray;
    public static ProtoMedia[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ProtoMedia[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 id = 1;
    public long id;

    // optional string data = 2;
    public java.lang.String data;

    // optional string title = 3;
    public java.lang.String title;

    // optional int64 duration = 4;
    public long duration;

    // optional string artist = 5;
    public java.lang.String artist;

    // optional string album = 6;
    public java.lang.String album;

    // optional string album_art = 7;
    public java.lang.String albumArt;

    // optional int32 track = 8;
    public int track;

    public ProtoMedia() {
      clear();
    }

    public ProtoMedia clear() {
      id = 0L;
      data = "";
      title = "";
      duration = 0L;
      artist = "";
      album = "";
      albumArt = "";
      track = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.id != 0L) {
        output.writeInt64(1, this.id);
      }
      if (!this.data.equals("")) {
        output.writeString(2, this.data);
      }
      if (!this.title.equals("")) {
        output.writeString(3, this.title);
      }
      if (this.duration != 0L) {
        output.writeInt64(4, this.duration);
      }
      if (!this.artist.equals("")) {
        output.writeString(5, this.artist);
      }
      if (!this.album.equals("")) {
        output.writeString(6, this.album);
      }
      if (!this.albumArt.equals("")) {
        output.writeString(7, this.albumArt);
      }
      if (this.track != 0) {
        output.writeInt32(8, this.track);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.id != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.id);
      }
      if (!this.data.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.data);
      }
      if (!this.title.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.title);
      }
      if (this.duration != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.duration);
      }
      if (!this.artist.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.artist);
      }
      if (!this.album.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.album);
      }
      if (!this.albumArt.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.albumArt);
      }
      if (this.track != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(8, this.track);
      }
      return size;
    }

    @Override
    public ProtoMedia mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.id = input.readInt64();
            break;
          }
          case 18: {
            this.data = input.readString();
            break;
          }
          case 26: {
            this.title = input.readString();
            break;
          }
          case 32: {
            this.duration = input.readInt64();
            break;
          }
          case 42: {
            this.artist = input.readString();
            break;
          }
          case 50: {
            this.album = input.readString();
            break;
          }
          case 58: {
            this.albumArt = input.readString();
            break;
          }
          case 64: {
            this.track = input.readInt32();
            break;
          }
        }
      }
    }

    public static ProtoMedia parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ProtoMedia(), data);
    }

    public static ProtoMedia parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ProtoMedia().mergeFrom(input);
    }
  }

  public static final class ProtoPlaylist extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ProtoPlaylist[] _emptyArray;
    public static ProtoPlaylist[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ProtoPlaylist[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .ProtoMedia playlist = 1;
    public com.doctoror.fuckoffmusicplayer.playlist.nano.PersistablePlaylist.ProtoMedia[] playlist;

    // optional int32 index = 2;
    public int index;

    // optional int64 position = 3;
    public long position;

    public ProtoPlaylist() {
      clear();
    }

    public ProtoPlaylist clear() {
      playlist = com.doctoror.fuckoffmusicplayer.playlist.nano.PersistablePlaylist.ProtoMedia.emptyArray();
      index = 0;
      position = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.playlist != null && this.playlist.length > 0) {
        for (int i = 0; i < this.playlist.length; i++) {
          com.doctoror.fuckoffmusicplayer.playlist.nano.PersistablePlaylist.ProtoMedia element = this.playlist[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      if (this.index != 0) {
        output.writeInt32(2, this.index);
      }
      if (this.position != 0L) {
        output.writeInt64(3, this.position);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.playlist != null && this.playlist.length > 0) {
        for (int i = 0; i < this.playlist.length; i++) {
          com.doctoror.fuckoffmusicplayer.playlist.nano.PersistablePlaylist.ProtoMedia element = this.playlist[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      if (this.index != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.index);
      }
      if (this.position != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.position);
      }
      return size;
    }

    @Override
    public ProtoPlaylist mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.playlist == null ? 0 : this.playlist.length;
            com.doctoror.fuckoffmusicplayer.playlist.nano.PersistablePlaylist.ProtoMedia[] newArray =
                new com.doctoror.fuckoffmusicplayer.playlist.nano.PersistablePlaylist.ProtoMedia[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.playlist, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.doctoror.fuckoffmusicplayer.playlist.nano.PersistablePlaylist.ProtoMedia();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.doctoror.fuckoffmusicplayer.playlist.nano.PersistablePlaylist.ProtoMedia();
            input.readMessage(newArray[i]);
            this.playlist = newArray;
            break;
          }
          case 16: {
            this.index = input.readInt32();
            break;
          }
          case 24: {
            this.position = input.readInt64();
            break;
          }
        }
      }
    }

    public static ProtoPlaylist parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ProtoPlaylist(), data);
    }

    public static ProtoPlaylist parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ProtoPlaylist().mergeFrom(input);
    }
  }
}
