// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.doctoror.fuckoffmusicplayer.playlist.nano;

@SuppressWarnings("hiding")
public interface RecentPlaylists {

  public static final class Albums extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Albums[] _emptyArray;
    public static Albums[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Albums[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated int64 ids = 1;
    public long[] ids;

    public Albums() {
      clear();
    }

    public Albums clear() {
      ids = com.google.protobuf.nano.WireFormatNano.EMPTY_LONG_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.ids != null && this.ids.length > 0) {
        for (int i = 0; i < this.ids.length; i++) {
          output.writeInt64(1, this.ids[i]);
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.ids != null && this.ids.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.ids.length; i++) {
          long element = this.ids[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt64SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * this.ids.length;
      }
      return size;
    }

    @Override
    public Albums mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 8);
            int i = this.ids == null ? 0 : this.ids.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.ids, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readInt64();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readInt64();
            this.ids = newArray;
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readInt64();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.ids == null ? 0 : this.ids.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.ids, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readInt64();
            }
            this.ids = newArray;
            input.popLimit(limit);
            break;
          }
        }
      }
    }

    public static Albums parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Albums(), data);
    }

    public static Albums parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Albums().mergeFrom(input);
    }
  }
}
